export default {
  ADD_ALERT: 'ADD_ALERT',
  ADD_FORM_ERROR: 'ADD_FORM_ERROR',
  CLEAR_FORM: 'CLEAR_FORM',
  CLEAR_USER: 'CLEAR_USER',
  CLOSE_MODAL: 'CLOSE_MODAL',
  CREATE_FORM: 'CREATE_FORM',
  DELETE_FORM_ERROM: 'DELETE_FORM_ERROR',
  EXPIRE_ALERT: 'EXPIRE_ALERT',
  FREEZE_UNFREEZE: 'FREEZE_UNFREEZE',
  HARD_DELETE_ALERT: 'HARD_DELETE_ALERT',
  LOGIN: 'LOGIN',
  OPEN_MODAL: 'OPEN_MODAL',
  SET_WINDOW_SIZE: 'SET_WINDOW_SIZE',
  SUBMIT_FORM: 'SUBMIT_FORM',
  UPDATE_FORM: 'UPDATE_FORM',
  UPDATE_TOTAL: 'UPDATE_TOTALS',
  UPDATE_USER: 'UPDATE_USER'
}
